GET http://localhost:5000/subscribers

//ดูข้อมูลในdatabase โดยเช็คแต่ละID
###
GET http://localhost:5000/subscribers/62622d552b0c199c76378a68

//เพิ่มข้อมูลเข้าbatabase
###
POST http://localhost:5000/subscribers
Content-Type: application/json

{
              "name":"the Hack Hon",
              "username":"Twin001",
              "password":"123456"
}

//ลบข้อมูลในbatabase ตามID
###
DELETE http://localhost:5000/subscribers/6262a5e9aaad37918964cc73

//updateข้อมูลในbatabase ตามID
###
PATCH http://localhost:5000/subscribers/62629710cda43149bb846a95
Content-Type: application/json

{
             "name":"Yutipat mata",
              "username":"Yutipat",
              "password":"123456" 
}